jdbc:
  driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/base1
    username: root
    password: 321000
  datasource2:
    url: jdbc:mysql://localhost:3306/base2
    username: root
    password: 321000
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file:
    name: spring.log
